name: lista_01
description: ExercÃ­cios feitos para o Lince Tech Academy.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.18.0 <3.0.0'

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
dependencies: 
  intl: ^0.17.0
